---
title: "US Consumer Data"
description: |
  ALL consumer data in one place
author:
  - name: Amber H
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo = FALSE, include=TRUE}

packages = c('readxl', 'tidyverse', 'ggridges', 'ggthemes')

for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p, character.only = T)
}
```


```{r, echo = FALSE, include=TRUE}
uom_cs <- readxl::read_xlsx(path = "/Users/yapinghuang/Desktop/Year 2024/macro/data/data.xlsx", sheet = "UOM_CS")

cpi <- readxl::read_xlsx(path = "/Users/yapinghuang/Desktop/Year 2024/macro/data/data.xlsx", sheet = "CPI(2)")

cpe <- readxl::read_xlsx(path = "/Users/yapinghuang/Desktop/Year 2024/macro/data/data.xlsx", sheet = "CPE")

job_claim <- readxl::read_xlsx(path = "/Users/yapinghuang/Desktop/Year 2024/macro/data/data.xlsx", sheet = "Jb_claim")

```

1. UOM Consumer Sentiment
Source: University of Michigan

```{r, echo = FALSE, fig.width=14, fig.height=8, include=TRUE}
ggplot(data = uom_cs, 
       aes(x = Release_Date, y = Actual)) +
  geom_line()+
  theme_economist()+
  labs(x = "Year",
       y = "Consumer Sentiment",
       title = "UOM Consumer Sentiment")
```

2. Consumer Price Index (CPI)
```{r, echo = FALSE, fig.width=14, fig.height=8, include=TRUE}

ggplot(data = cpi, 
       aes(x = Date, y = CPI)) +
  geom_line()+
  theme_economist()+
  labs(x = "Year",
       y = "CPI",
       title = "CPI since 2020")
```

3. Personal Consumption Expenditures Price Index (PCE)

```{r, echo = FALSE, fig.width=6, fig.height=4, include=TRUE}

start_date <- as.POSIXct("2019-01-01")
end_date <- as.POSIXct("2023-11-01")
cpe <- cpe[cpe$observation_date >= start_date & cpe$observation_date <= end_date,]

ggplot(data = cpe, 
       aes(x = observation_date, y = PCE)) +
  geom_line()+
  theme_economist()+
  labs(x = "Year",
       y = "CPE",
       title = "Personal Consumption Expenditures")
```


4. Continued Claims (Insured Unemployment) (CCSA)

```{r, echo = FALSE, fig.width=6, fig.height=4, include=TRUE}

start_date <- as.POSIXct("2019-01-01")
end_date <- as.POSIXct("2023-12-09")
job_claim <- job_claim [job_claim$date >= start_date & job_claim$date <= end_date,]
job_claim$CCSA_in_millions <- job_claim$CCSA / 1e6

ggplot(data = job_claim, 
       aes(x = date, y = CCSA_in_millions)) +
  geom_line()+
  theme_economist()+
  labs(x = "Year",
       y = "CCSA in millions",
       title = "Weekly Continued Claims")
```