---
title: "GDP Growth Rate"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css}
.figure {
  text-align: center;
}
.figure p {
  font-size: 18px;
}
```

```{r, echo = FALSE, include=TRUE}

packages = c('readxl', 'tidyverse', 'ggridges', 'ggthemes')

for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p, character.only = T)
}
```


```{r, echo = FALSE, include=TRUE}
us_gdp <- readxl::read_xls(path = "/Users/yapinghuang/Desktop/Year 2024/macro/data/GDP.xls")
gdp_g <- readxl::read_xlsx(path = "/Users/yapinghuang/Desktop/Year 2024/macro/data/data.xlsx", sheet = "GDP_growth")

```

1. US GDP

Source: U.S. Bureau of Economic Analysis  

Gross domestic product (GDP), the featured measure of U.S. output, is the market value of the goods and services produced by labor and property located in the United States.

```{r, echo = FALSE, fig.width=16, fig.height=12, include=TRUE}

start_date <- as.POSIXct("2019-01-01")
us_gdp <- us_gdp[us_gdp$observation_date >= start_date,]

ggplot(data = us_gdp, 
       aes(x = observation_date, y = GDP)) +
  geom_line()+
  theme_economist()+
  labs(x = "Year",
       y = "GDP in Billions",
       title = "US GDP")

```


2. Real GDP growth Annual percent change

Source: IMF (https://www.imf.org/external/datamapper/NGDP_RPCH@WEO/OEMDC/ADVEC)


```{r, echo = FALSE, fig.width=16, fig.height=12, include=TRUE}

ggplot(data = gdp_g, 
       aes(x = Year, y= countries)) +
  geom_line(aes(y = US), color = "red", linetype = "dashed")+
  geom_line(aes(y = Japan, color = "blue", linetype = "dotted"))+
  geom_line(aes(y = China), color = "black")+
  theme_economist()+
  labs(x = "Year",
       y = "GDP Growth %",
       title = "GDP Growth for United States, Japan, China")+
  theme(legend.position = "none")

```
